### ISSUE TITLE
Undefined array key "first" error after v2.5.1

### ISSUE THREAD

**Issue by kjmartens** [putyourlightson/craft-plugin-sales#5]
Hi @bencroker,

Thank you for this excellent plugin, btw! 🙂 

The last version I can get working is 2.5.1. Anything after that, I get this error when accessing the main dashboard `/admin/plugin-sales`). It looks like you've maybe run into this issue before, judging by the fixes in the changelog, but nothing, including v2.7.3, resolves this issue. Running Craft Pro 4.4.16.1 (but it happened on versions before that).

```
yii\base\ErrorException: Undefined array key "first" in /MYPATH-REMOVED/vendor/putyourlightson/craft-plugin-sales/src/services/ReportsService.php:48
Stack trace:
#0 /MYPATH-REMOVED/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '/Users/kmartens...', 48)
#1 /MYPATH-REMOVED/vendor/putyourlightson/craft-plugin-sales/src/services/ReportsService.php(48): craft\web\ErrorHandler->handleError(2, 'Undefined array...', '/Users/kmartens...', 48)
#2 /MYPATH-REMOVED/vendor/twig/twig/src/Extension/CoreExtension.php(1607): putyourlightson\pluginsales\services\ReportsService->getSalesData(NULL, NULL)
#3 /MYPATH-REMOVED/vendor/craftcms/cms/src/helpers/Template.php(146): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(putyourlightson\pluginsales\services\ReportsService), 'getSalesData', Array, 'method', false, false)
#4 /MYPATH-REMOVED/storage/runtime/compiled_templates/cb/cbf1788dc991e41eab87d755068504183f4e1dce2d330c235a0a8491ef969321.php(173): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(putyourlightson\pluginsales\services\ReportsService), 'getSalesData', Array, 'method')
#5 /MYPATH-REMOVED/vendor/twig/twig/src/Template.php(394): __TwigTemplate_e8988a8bf32254d079b746a4646732c1ebe2b51b40cdfa499cd8e410af054763->doDisplay(Array, Array)
#6 /MYPATH-REMOVED/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#7 /MYPATH-REMOVED/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#8 /MYPATH-REMOVED/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#9 /MYPATH-REMOVED/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#10 /MYPATH-REMOVED/vendor/craftcms/cms/src/web/View.php(465): Twig\Environment->render('plugin-sales', Array)
#11 /MYPATH-REMOVED/vendor/craftcms/cms/src/web/View.php(518): craft\web\View->renderTemplate('plugin-sales', Array)
#12 /MYPATH-REMOVED/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(56): craft\web\View->renderPageTemplate('plugin-sales', Array, 'cp')
#13 /MYPATH-REMOVED/vendor/yiisoft/yii2/web/Response.php(1098): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#14 /MYPATH-REMOVED/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#15 /MYPATH-REMOVED/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#16 /MYPATH-REMOVED/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#17 /MYPATH-REMOVED/web/index.php(21): yii\base\Application->run()
#18 {main}
```

**Comment by bencroker** [comment]
Sounds like this migration may not have been successfully executed in your setup, added in 2.6.0:
https://github.com/putyourlightson/craft-plugin-sales/blob/develop/src/migrations/m221213_120000_add_first_column.php
